### ISSUE TITLE
Bug Report: Last node LTS is 22

### ISSUE THREAD

**Issue by benoittgt** [CircleCI-Public/cimg-ruby#186]
**Describe the bug**
At the moment the last Node LTS is 22.11.0, but we install version 20.

I tried to use the [orb](https://github.com/circleci-public/node-orb) but it failed because of yarn version mismatch:

```
Latest version of Yarn is 1.22.22
Checking if YARN is already installed...
A different version of Yarn is installed (1.22.19); removing it
^@^@rm: cannot remove '/usr/local/bin/yarn': Permission denied

Exited with code exit status 1
```

**To Reproduce**

```yaml
version: 2.1

orbs:
  ruby: circleci/ruby@2
  node: circleci/node@6

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.5-browsers
    steps:
      - checkout
      - node/install:
          install-yarn: true

workflows:
  version: 2
  main:
    jobs:
      - build
```

In my `.nvmrc` `22.11.0`. 

**Expected behavior**

I am able to use Node 22.

**Workarounds**

Use my own Ruby image.
