### ISSUE TITLE
Can't install the sqlite3 gem because libsqlite3-dev is not installed

### ISSUE THREAD

**Issue by jcoyne** [CircleCI-Public/cimg-ruby#64]
When I was attempting to upgrade from `circleci/ruby` to `cimg/ruby` I was unable to run my Rails application which tests on sqlite3. 

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2/ext/sqlite3
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.7.0 -r
./siteconf20210629-509-1habn66.rb extconf.rb
checking for sqlite3.h... no
sqlite3.h is missing. Try 'brew install sqlite3',
'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
and check your shared library search path (the
location where your sqlite3 shared library is located).
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--with-sqlcipher
	--without-sqlcipher
	--with-sqlite3-config
	--without-sqlite3-config
	--with-pkg-config
	--without-pkg-config
	--with-sqlcipher
	--without-sqlcipher
	--with-sqlite3-dir
	--without-sqlite3-dir
	--with-sqlite3-include
	--without-sqlite3-include=${sqlite3-dir}/include
	--with-sqlite3-lib
	--without-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/home/circleci/project/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0-static/sqlite3-1.4.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/sqlite3-1.4.2 for
inspection.
Results logged to
/home/circleci/project/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0-static/sqlite3-1.4.2/gem_make.out

An error occurred while installing sqlite3 (1.4.2), and Bundler cannot
continue.
Make sure that `gem install sqlite3 -v '1.4.2' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  sqlite3

Exited with code exit status 5
```

**Comment by shouichi** [comment]
SQLite is fairly common. It would be beneficial for many of us if its dependencies are installed in the image. @felicianotech Could you consider this?

**Comment by purp** [comment]
This can be handled in your `.circleci/config.yml` file, per [the advanced config docs](https://circleci.com/docs/2.0/adv-config/). Here's what mine looks like now:

```
[...]
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
    executor: ruby/default
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install sqlite3 libsqlite3-dev
      - run:
          name: Which bundler?
[...]
```

Took a bit to find the right docs for this; would sure be nice to add some hinting in the default `config.yml` that comes with the super-smooth, very awesome new user experience.
