### ISSUE TITLE
ruby with node 16 lts

### ISSUE THREAD

**Issue by aleksandrlat** [CircleCI-Public/cimg-ruby#70]
Node js version 14 is old lts version. We want to migrate to new node but have to build image manually
It would be great to have pre-built ruby with new node lts 16

**Comment by guillaumebriday-pa** [comment]
That would be awesome! @jordan-brough

**Comment by jordan-brough** [comment]
It looks like `circleci/ruby` has already gotten this update, but `cimg/ruby` has not.

```sh
$ docker pull circleci/ruby:3.0.2-node-browsers
$ docker run -it --rm circleci/ruby:3.0.2-node-browsers node --version
v16.13.0
```

```sh
$ docker pull cimg/ruby:2.7-browsers
$ docker run -it --rm cimg/ruby:2.7-browsers node --version
v14.17.3
```

`cimg/ruby` is supposed to replace `circleci/ruby`, right? 
> This image is designed to supercede the legacy CircleCI Ruby image, circleci/ruby

https://circleci.com/developer/images/image/cimg/ruby

**Comment by vietqhoang** [comment]
Just want to chime in that we would like node 16 available in the Ruby image, specifically the browser variant of ruby 3.0.2.

We actually just updated from node 14 to 16 on our project as a result of the deprecated `circleci/ruby` image having updated to 16 just recently.

We are in the process of migrating to the new convenience images, but due to updating to node 16 in our project to accommodate the deprecated ruby image, we are now at a confusing roadblock.

**Comment by mattbrictson** [comment]
I can't speak to Circle's official recommendation, but on my team we are successfully using the node orb to manage our node version explicitly. I like that this gives us complete control over what node version is installed, rather than getting stuck with whatever `cimg/ruby` provides.

```yaml
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
          node-version: "16.13.0"
```

**Comment by vietqhoang** [comment]
> I can't speak to Circle's official recommendation, but on my team we are successfully using the node orb to manage our node version explicitly. I like that this gives us complete control over what node version is installed, rather than getting stuck with whatever `cimg/ruby` provides.
> 
> ```yaml
> orbs:
>   node: circleci/node@4.7.0
> jobs:
>   build:
>     docker:
>       - image: cimg/ruby:3.0.2
>     steps:
>       - checkout
>       - node/install:
>           install-yarn: true
>           install-npm: false
>           node-version: "16.13.0"
> ```

Thanks for the suggestion.

Have you experimented with using the Node orb (or Docker image) on top of the browser variant of the image? The browser variant, which comes with a version of Node, also comes with browser related software (namely Selenium). Our app utilizes Selenium for our test suite. I wonder if applying a Node orb/Docker image on top of a Ruby image that comes with a version of Node would work?

I'll give it a try.

**Comment by mattbrictson** [comment]
> Have you experimented with using the Node orb (or Docker image) on top of the browser variant of the image?

@vietqhoang Yes. I left it out of my example, but we are using `cimg/ruby:3.0.2-browsers` coupled with the `browser-tools` orb (`install-chrome`, `install-chromedriver`) for running our selenium tests. And we use the node orb on top of that to install the desired version of node. It works great.

**Comment by jon-sully** [comment]
> I can't speak to Circle's official recommendation, but on my team we are successfully using the node orb to manage our node version explicitly. I like that this gives us complete control over what node version is installed, rather than getting stuck with whatever `cimg/ruby` provides.
> 
> ```yaml
> orbs:
>   node: circleci/node@4.7.0
> jobs:
>   build:
>     docker:
>       - image: cimg/ruby:3.0.2
>     steps:
>       - checkout
>       - node/install:
>           install-yarn: true
>           install-npm: false
>           node-version: "16.13.0"
> ```

Nice. I tried to get the Node _image_ working with the right version but this works great. Thanks!

**Comment by jon-sully** [comment]
Actually, a note there for others ^ the Node install can leave some files in the `project/` folder so (as noted in the example) make sure you do it _after_ the `checkout` step otherwise the `checkout` will fail:

```
Directory (/home/circleci/project) you are trying to checkout to is not empty and not a git repository
```

**Comment by felicianotech** [comment]
Hey everyone,

For next-gen Convenience Images (such as `cimg/ruby`) we don't respin images as a standard practice. In this scenario, I know some of you would like a newer Node.js LTS version. There's going to be plenty of people using these images that need the version that's in the image now. If we update the images, those people's pipelines break.

As such, the version of Node.js that a node variant image ships with is what it has. That doesn't change. Now that the Node.js LTS has been updated, the next time a Ruby image is released by us, it will automatically pick up the new LTS version. So for example, if/when Ruby v3.0.3 comes, it will have Node.js v16.

In the meantime, if you need a different/newer Node.js version in the image, yes the suggestion is to use to [Node.js Orb](https://circleci.com/developer/orbs/orb/circleci/node) to swap the version.

@jon-sully Interesting. Do you mind posting your findings as a [Node.js Orb Issue](https://github.com/CircleCI-Public/node-orb/issues) so that we can take a look? I haven't looked at that code myself yet but that doesn't sound like a good idea to leave files behind in ~/project.

**Comment by jordan-brough** [comment]
> if/when Ruby v3.0.3 comes, it will have Node.js v16

That's fairly surprising from an end user point of view for what appears to be a patch-level update (3.0.2 -> 3.0.3).

Have you considered some form of tagging to make that a little less surprising?  E.g. maybe:
- `3.0.2-node-14`
- `3.0.2-node-16`
?

That might:
1. Allow you to push out new versions even when there is an important Node update but a long period of time between Ruby updates
2. Be less surprising and more consistent for people who either want their images to stay the same or want to get the updated Node version

**Comment by jon-sully** [comment]
> @jon-sully Interesting. Do you mind posting your findings as a Node.js Orb Issue so that we can take a look? I haven't looked at that code myself yet but that doesn't sound like a good idea to leave files behind in ~/project.

I went to do this and realized I'm at least one major version behind on the Node orb. Going to disregard myself for now. Thanks!

> Have you considered some form of tagging to make that a little less surprising? E.g. maybe:

I get where this idea is coming from but I think at that level of complexity it's no longer just a nice image that includes node as a quick little helping-moment and is more of a burden. At that point why not just pull in the Node image ourselves and install the specific version we want 🤔

**Comment by jordan-brough** [comment]
> it's no longer just a nice image that includes node as a quick little helping-moment and is more of a burden

You could still have `3.0.2-node` as tag that gives "whatever the version of Node was when we released it".

**Comment by felicianotech** [comment]
@jordan-brough I still think the Node.js orb is really the best solution here. With it, you specific exactly what you want. If the image already has that version great, if not, it will install it for you.

Your idea does sound interesting though and is something I'd like to think more about with the team so I created a [GitHub Issue](https://github.com/CircleCI-Public/cimg-shared/issues/43) to track it. There's pros and cons with this concept so it's something to think about further.

**Comment by jordan-brough** [comment]
What would the yaml be for configuring a "browsers" version with Ruby 3.0.2 and Node 16?

Would it be something like this? (I haven't tried it out yet...)
```yaml
orbs:
  node: circleci/node@4.7.0
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
          node-version: "16.13.0"
      - browser-tools/install-browser-tools
```
?

**Comment by felicianotech** [comment]
Close. If you just wanted both browsers, what you have is good, but I would just change the image tag to this:

`cimg/ruby:3.0.2-browsers`

If you wanted just Chrome, you could make it a little faster by doing this:

```yaml
orbs:
  node: circleci/node@4.7.0
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2-browsers
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
          node-version: "16.13.0"
      - browser-tools/install-chrome
      - -browser-tools/install-chromedriver
```

Basically the latter avoids Firefox and Geckodriver installs if you don't need them.

**Comment by jordan-brough** [comment]
Thank you!

> `- -browser-tools/install-chromedriver`

Should that be `- browser-tools/install-chromedriver`?

So `cimg/ruby:3.0.2-browsers` includes Node 14, and then the node orb will install Node 16 over the top of that, is that right? That sounds a little messy (possibly error-prone?) to me, but since you're recommending it I assume it'll work out ok?

A few things are jumping out to me at the moment:
* I assume, having to install Node & browsers on every test run is slower than pulling down a prepared docker image? (And easier than setting up some caching)
* That's a lot more version numbers to keep on top of (the two orb versions, and the Node minor + patch versions, in addition to the Ruby & Node versions) than it would be to just have a tag like `3.0.2-node-16-browsers`, which would result in just this, right?
    ```yaml
    jobs:
      build:
        docker:
          - image: cimg/ruby:3.0-node-14-browsers
    ```

It seems like a very common use case here is a Rails app doing asset compilation (and possibly browser testing) where both the Ruby version and the Node version are important.  I would think specifying at least the major version for both Ruby and Node would be a best practice that CircleCI would want to encourage or at least enable?
