### ISSUE TITLE
Ruby with ImageMagick

### ISSUE THREAD

**Issue by vietqhoang** [CircleCI-Public/cimg-ruby#71]
It looks like the deprecated image `circleci/ruby` comes packaged with ImageMagick, while the convenience images do not.

Are there plans on including library with the convenience image?

Our use case is for our Rails application which makes use of Rail's [ActiveStorage](https://edgeguides.rubyonrails.org/active_storage_overview.html). The dependency of `ImageMagick` comes from one of the [requirements to be able to use the image analysis and transformation functionality](https://edgeguides.rubyonrails.org/active_storage_overview.html#requirements) of the library. Namely, ActiveStorage's dependency on `image_processing` which uses either ImageMagick or GraphicsMagick.

**Comment by jon-sully** [comment]
FWIW I just migrated us to `cimg/ruby` from `circleci/ruby` and found a loss in both ImageMagick and chromedriver (both were included in `circleci/ruby-stretch-node` or whatever it was called). Imagemagick I just installed with its own discrete step:

```yml
    steps:
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install imagemagick
```

And the chromedriver / selenium stuff was pushed over to its own orb, Browser Tools: https://circleci.com/developer/orbs/orb/circleci/browser-tools. Adding that to my orbs list and running the baseline step

```yml
    steps:
      - browser-tools/install-browser-tools
```

Fixed it for me.

While I certainly don't know Circle's goals, I imagine the intention with `cimg/ruby` is specifically to not include as much 'extra' software since many installations simply don't need it. More legos, less magic.
