### ISSUE TITLE
Support Ruby shell

### ISSUE THREAD

**Issue by jkzilla** [CircleCI-Public/cimg-ruby#78]
description: >
Test ruby
steps:
- run:
shell: /usr/local/bin/ruby
command: |
puts "hello"
and the error we're receiving is something like:

/usr/local/bin/ruby: No such file or directory -- puts 'hello' (LoadError)

**Comment by felicianotech** [comment]
Hey @jkzilla I think we talked about this before. From what I remember, this request would need to be handled by CircleCI's build-agent and not here. Please correct me if I'm wrong.

**Comment by kelvintaywl** [comment]
for reference, this is now possible on CircleCI, and is not related to this image.

```yaml
# example

jobs:
  ruby:
    environment:
      FOO: bar
    docker:
      - image: cimg/ruby:2.7
    steps:
      - run:
          name: print FOO
          shell: ruby
          command: |
            puts ENV["FOO"]
```
